[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"

[workspace]
members = ["programs/cp-swap"]

[features]
seeds = false
skip-lint = false

[programs.localnet]
raydium_cp_swap = "WFHgqbEBAESXYu9EWcnpDcLoG9L5kDyQJjCG3a5AGqL"

[programs.devnet]
raydium_cp_swap = "WFHgqbEBAESXYu9EWcnpDcLoG9L5kDyQJjCG3a5AGqL"

[registry]
url = "https://github.com/raydium-io/raydium-cp-swap"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"

[test]
startup_wait = 10000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "DNXgeM9EiiaAbaWvwjHj9fQQLAX5ZsfHyvmYUNRAdNC8" # pool fee receiver

[[test.validator.clone]]
address = "D4FPEruKEHrG5TenZ2mpDGEfu1iUvTiqBxvpU8HLBvC2" # index 0 AMM Config account
